name: SLSA Go releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write      # Necessário para assinar a release.
  contents: write      # Necessário para enviar os artefatos do release.
  actions: read        # Para ler o caminho do workflow.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Step 3: Install the SLSA Go Releaser
      - name: Install SLSA Releaser
        run: |
          curl -sSL https://github.com/slsa-framework/slsa-goreleaser/releases/download/v1.0.0/slsa-goreleaser-linux-amd64 -o /usr/local/bin/slsa-goreleaser
          chmod +x /usr/local/bin/slsa-goreleaser

      # Step 4: Run the SLSA Go Releaser to build and release
      - name: Run SLSA Go Releaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          slsa-goreleaser build --id-token="${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}" --binary=myapp

